/**
 * start.js — Production entry point for whogohost / shared Node.js hosting.
 *
 * The Next.js standalone server (.next/standalone/server.js) does NOT load
 * .env files — it relies on environment variables already being present in
 * the process. On shared hosts that don't inject env vars automatically we
 * must load them ourselves before Next.js boots.
 *
 * Point your hosting panel's "startup file" to this file (start.js),
 * NOT to .next/standalone/server.js directly.
 */

const path = require("path");

// Load .env.production from the project root BEFORE anything else runs.
// dotenv silently no-ops if the file is missing, so this is safe.
require("dotenv").config({
  path: path.join(__dirname, ".env.production"),
});

// Hand off to the Next.js standalone server.
// This file is auto-generated by `next build` when output: "standalone" is set.
require(path.join(__dirname, ".next", "standalone", "server.js"));
